Initial pass at unification into a generic grub loopback-iso hook

diff --git a/42_grml b/42_grml
--- a/42_grml
+++ b/42_grml
@@ -1,6 +1,6 @@
 #!/bin/sh
-# Filename:      42_grml
-# Purpose:       grub-mkconfig helper script for Grml rescue systems
+# Filename:      loopback-iso
+# Purpose:       grub-mkconfig helper script for loopback.cfg-compatible ISOs
 # Authors:       Grml team (grml.org), (c) Andreas Gredler <jimmy@grml.org>, Michael Prokop <mika@grml.org>
 # License:       This file is licensed under the GPL v2+.
 ################################################################################
@@ -12,19 +12,47 @@ exec_prefix=${prefix}
 bindir=${exec_prefix}/bin
 libdir=${exec_prefix}/lib
 
+progname="loopback-iso"
+default_file="/etc/default/grub"
+default_dir="/etc/default/grub.d"
+
 if [ -r ${libdir}/grub/grub-mkconfig_lib ] ; then
   . ${libdir}/grub/grub-mkconfig_lib
 elif [ -r /usr/share/grub/grub-mkconfig_lib ] ; then # fallback for e.g. Fedora
   . /usr/share/grub/grub-mkconfig_lib
 else
-  echo "Could not locate file grub-mkconfig_lib, please report a bug." >&2
+  echo "${progname}: Could not locate file grub-mkconfig_lib, please report a bug." >&2
+  exit 0
 fi
 
-# default unless configured otherwise:
-ISO_LOCATION="/boot/grml"
+# Sadly, grub-mkconfig does not export all GRUB_* variables, so we
+# must re-source the default files.
+for cfg in "${default_file}" "${default_dir}"/*.cfg ; do
+  if test -r "${cfg}"; then
+    . "${cfg}"
+  fi
+done
 
+# Support grml-rescueboot-specific configuration location / variable names
 if [ -r /etc/default/grml-rescueboot ] ; then
   . /etc/default/grml-rescueboot
+  GRUB_LOOPBACK_ISO_PARAMS="${CUSTOM_BOOTOPTIONS}"
+  if [ -n "${ISO_LOCATION}" ]; then
+    GRUB_LOOPBACK_ISO_LOCATION="${ISO_LOCATION}"
+  elif [ -d /boot/grml ]; then
+    GRUB_LOOPBACK_ISO_LOCATION="/boot/grml"
+  fi
+fi
+
+if [ -n "${GRUB_LOOPBACK_ISO_LOCATION}" ] && [ ! -d "${GRUB_LOOPBACK_ISO_LOCATION}" ]; then
+  # If explicitly provided but does not exist, exit 0
+  echo "${progname}: Cannot find ${GRUB_LOOPBACK_ISO_LOCATION}" >&2
+  exit 0
+elif [ -d /boot/loopback-iso ]; then
+  GRUB_LOOPBACK_ISO_LOCATION="/boot/loopback-iso"
+else
+  # Exit silently if there's nothing to do
+  exit 0
 fi
 
 resolve_dm_name() {
@@ -79,17 +107,13 @@ get_dependencies() {
 
 
 
-iso_list=""
-for file in "${ISO_LOCATION}"/*.iso ; do
-     if grub_file_is_not_garbage "$file" ; then
-       iso_list="$iso_list $file "
-     fi
-done
-
-for grmliso in $iso_list ; do
-  rel_dirname="$(dirname $(make_system_path_relative_to_its_root $grmliso))"
-  grml="$(basename $grmliso)"
-  device="$(${grub_probe} -t device ${grmliso})"
+for iso in "${GRUB_LOOPBACK_ISO_LOCATION}"/*.iso ; do
+  if ! grub_file_is_not_garbage "${iso}" ; then
+    continue
+  fi
+  rel_dirname="$(dirname "$(make_system_path_relative_to_its_root "${iso}")")"
+  iso_base="$(basename "${iso}")"
+  device="$(${grub_probe} -t device "${iso}")"
 
   additional_param=""
 
@@ -105,18 +129,23 @@ for grmliso in $iso_list ; do
     ;;
   esac
 
-  echo "Found Grml ISO image: $grmliso" >&2
-  title="Grml Rescue System ($grml)"
+  if [ "$(echo "${iso_base}" | awk '{print substr($0, 1, 4)}')" = "grml" ]; then
+    title_type="Grml Rescue System image"
+  else
+    title_type="ISO image"
+  fi
+  echo "${progname}: Found ${title_type}: ${iso}" >&2
+  title="${title_type} (${iso_base})"
   grub_prep=$(prepare_grub_to_access_device "$device" | sed -e "s/^/        /")
 
   cat << EOF
 menuentry "${title}" {
 ${grub_prep}
-        iso_path="${rel_dirname%/}/${grml}"
+        iso_path="${rel_dirname%/}/${iso_base}"
         export iso_path
-        kernelopts=" $CUSTOM_BOOTOPTIONS $additional_param "
+        kernelopts=" ${GRUB_LOOPBACK_ISO_PARAMS} ${additional_param} "
         export kernelopts
-        loopback loop "${rel_dirname%/}/$grml"
+        loopback loop "${rel_dirname%/}/${iso_base}"
         set root=(loop)
         configfile /boot/grub/loopback.cfg
 }
